---
- name: Configure Network Devices
  hosts: network_devices
  gather_facts: no
  tasks:
    - name: Apply Configuration to Router
      ios_config:
        lines:
          - hostname Router1
          - interface GigabitEthernet0/1
          - ip address 192.168.1.1 255.255.255.0
